playlist:
    path:     /client/playlist
    defaults: { _controller: "MmiBackBundle:Playlist:index" }

playlist_show:
    path:     /client/playlist/{idp}/show
    defaults: { _controller: "MmiBackBundle:Playlist:show" }

playlist_new:
    path:     /client/playlist/new
    defaults: { _controller: "MmiBackBundle:Playlist:new" }

playlist_create:
    path:     /client/playlist/create
    defaults: { _controller: "MmiBackBundle:Playlist:create" }
    methods:  POST

playlist_edit:
    path:     /client/playlist/{idp}/edit
    defaults: { _controller: "MmiBackBundle:Playlist:edit" }

playlist_update:
    path:     /client/playlist/{idp}/update
    defaults: { _controller: "MmiBackBundle:Playlist:update" }
    methods:  [POST, PUT]

playlist_delete:
    path:     /client/playlist/{idp}/delete
    defaults: { _controller: "MmiBackBundle:Playlist:delete" }
    methods:  [POST, DELETE]

admin_playlist:
    path:     /admin/playlist
    defaults: { _controller: "MmiBackBundle:Playlist:index" }
