<?php

namespace Mmi\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusRepository extends EntityRepository
{
}
